spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sales_service
    username: root
    password: Ilove98u
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: "your_email@gmail.com"   # Replace with your actual Gmail address
    password: "app_password"           # Replace with your Gmail app-specific password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

base:
  url: "http://localhost:8080"

# Security settings (optional for user authentication) yet to code
security:
  user:
    name: admin
    password: adminpassword

sales-service:
  api:
    version: v1
  order:
    email-notification: true
  payment:
    gateway: paypal
    currency: USD
